crm/urls.py
from django.contrib import admin
from django.urls import path

from salesleads.views import (
    LoginView,
    LogoutView,
    UserListView,
    SalesLeadAddFormView,
    SalesLeadListView,
    SalesLeadDetailView,
    SearchResults,
    SalesLeadMap,
    DashboardView,
    SalesLeadDelete,
    ContactPersonDelete,
    PlannedActitivitiesDelete,
    CommentDelete,
    CommentUpdate,
    ContactPersonUpdate,
    PlannedActivitiesUpdate,
    country_create,
    ReportView,
    ChangeUserView,
    SalesLeadModalDelete,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/', UserListView.as_view(), name='users'),
    path('contactperson_delete/<int:contactperson_id>', ContactPersonDelete.as_view(), name='contactperson-delete'),
    path('contactperson_update/<int:contactperson_id>', ContactPersonUpdate.as_view(), name='contactperson-update'),
    path('comment_delete/<int:comment_id>', CommentDelete.as_view(), name='comment-delete'),
    path('comment_update/<int:comment_id>', CommentUpdate.as_view(), name='comment-update'),
    path('plannedactivities_delete/<int:plannedactivity_id>', PlannedActitivitiesDelete.as_view(), name='plannedactivity-delete'),
    path('plannedactivities_update/<int:plannedactivities_id>', PlannedActivitiesUpdate.as_view(), name='plannedactivity-update'),
    path('saleslead_add/', SalesLeadAddFormView.as_view(), name='saleslead-add'),
    path('saleslead_delete/<int:saleslead_id>', SalesLeadDelete.as_view(), name='saleslead-delete'),
    path('saleslead_delete2/<int:saleslead_id>', SalesLeadModalDelete.as_view(), name='saleslead-delete-modal'),
    path('salesleads/', SalesLeadListView.as_view(), name='salesleads'),
    path('saleslead_detail/<int:saleslead_id>/', SalesLeadDetailView.as_view(), name='saleslead-detail'),
    path('search_results/', SearchResults.as_view(), name='search-results'),
    path('map/', SalesLeadMap.as_view(), name='map'),
    path('', DashboardView.as_view(), name='dashboard'),
    path('country_create/', country_create, name='country-create'),
    path('report/', ReportView.as_view(), name='report'),
    path('user_change/<int:saleslead_id>/', ChangeUserView.as_view(), name='user-change')
]

salesleads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.gis.db import models
from simple_history.models import HistoricalRecords

MARKETS = (
    (1, 'ME-DE'),
    (2, 'ME-IT'),
    (3, 'ME-NL'),
    (4, 'ME-PE'),
    (5, 'ME-RU')
)

SOURCES = (
    (1, 'targi'),
    (2, 'internet'),
    (3, 'linkedin'),
    (4, 'inne')
)

STATUS = (
    (1, 'Pierwsze zamówienie'),
    (2, 'Złożone warunki/oferta'),
    (3, 'Najbardziej obiecujące'),
    (4, 'Pozostałe Aktywności'),
    (5, 'Odrzucone')
)

SCORE = (
    (1, 1),
    (2, 2),
    (3, 3),
    (4, 4),
    (5, 5)
)

TYPES = (
    (1, 'Nowy klient'),
    (2, 'Rozszerzenie oferty'),
    (3, 'Historyczny klient'),
)

ACTIVITIES = (
    (1, 'Kontakt telefoniczny'),
    (2, 'E-mail'),
    (3, 'Spotkanie')
)

POTENTIAL = (
    (1, 'do 5.000 Eur'),
    (2, '5.000 - 10.000 Eur'),
    (3, '10.000 - 25.000 Eur'),
    (4, '25.000 - 50.000 Eur'),
    (5, '50.000 - 75.000 Eur'),
    (6, '75.000 - 100.000 Eur'),
    (7, '100.000 - 125.000 Eur'),
    (8, '125.000 - 150.000 Eur'),
    (9, '150.000 - 200.000 Eur'),
    (10, '200.000 - 250.000 Eur'),
    (11, 'Powyżej 250.000 Eur')
)


class ExportUser(AbstractUser):
    market = models.IntegerField(choices=MARKETS, verbose_name='rynek', null=True, blank=True)

    def __str__(self):
        return self.username


class Country(models.Model):
    country = models.CharField(max_length=128)

    def __str__(self):
        return self.country

    class Meta:
        ordering = ['country']
        verbose_name = 'Kraj'
        verbose_name_plural = 'Kraje'


class SalesLead(models.Model):
    user = models.ForeignKey(ExportUser, null=True, blank=True, on_delete=models.PROTECT)
    type = models.IntegerField(choices=TYPES, null=True, verbose_name='Typ')
    status = models.IntegerField(choices=STATUS, null=True)
    company_name = models.CharField(max_length=65, null=True, verbose_name='Nazwa firmy')
    location = models.PointField(null=True, blank=True)
    latitude = models.CharField(null=True, blank=True, max_length=128, verbose_name='Wysokość')
    longtitude = models.CharField(null=True, blank=True, max_length=128, verbose_name='Szerokość')
    street = models.CharField(max_length=256, null=True, blank=True, verbose_name='Ulica')
    city = models.CharField(max_length=128, null=True, blank=True, verbose_name='Miejscowość')
    postcode = models.IntegerField(null=True, blank=True, verbose_name='Kod pocztowy')
    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=True, verbose_name='Kraj')
    company_website = models.URLField(null=True, blank=True, verbose_name='Strona www')
    source = models.IntegerField(choices=SOURCES, null=True, blank=True, verbose_name='Źródło')
    brands = models.CharField(max_length=256, null=True, blank=True, verbose_name='Referencje')
    potential = models.IntegerField(choices=POTENTIAL, null=True, blank=True, verbose_name='Potencjał')
    score = models.IntegerField(choices=SCORE, null=True, verbose_name='Ocena', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    history = HistoricalRecords()

    def __str__(self):
        return self.company_name

    @property
    def lat_lng(self):
        return list(getattr(self.location, 'coords', [])[::-1])

    class Meta:
        ordering = ['company_name']


class Comment(models.Model):
    saleslead = models.ForeignKey(SalesLead, on_delete=models.PROTECT, related_name='comment', null=True)
    comment = models.TextField(verbose_name='Komentarz', null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    modified = models.DateTimeField(auto_now=True, null=True)
    history = HistoricalRecords()

    def __str__(self):
        return self.comment

    class Meta:
        ordering = ['-created']


class ContactPerson(models.Model):
    saleslead = models.ForeignKey(SalesLead, on_delete=models.PROTECT, related_name='contacts')
    first_name = models.CharField(max_length=64, null=True, verbose_name='Imię', blank=True)
    last_name = models.CharField(max_length=128, null=True, verbose_name='Nazwisko', blank=True)
    position = models.CharField(max_length=128, null=True, verbose_name='Stanowisko', blank=True)
    email = models.EmailField(null=True, blank=True)
    telephone = models.IntegerField(null=True, verbose_name='Telefon', blank=True)
    whatsapp = models.IntegerField(null=True, verbose_name='WhatsApp', blank=True)
    linkedin_added = models.BooleanField(verbose_name='Kontakt Linkedin', null=True, blank=True)
    default = models.BooleanField(verbose_name='Kontakt domyślny', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    history = HistoricalRecords()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class PlannedActivities(models.Model):
    user = models.ForeignKey(ExportUser, null=True, blank=True, on_delete=models.PROTECT)
    saleslead = models.ForeignKey(SalesLead, on_delete=models.CASCADE, related_name='plannedactivities')
    date = models.DateField(null=True, blank=True, verbose_name='Data')
    activity_type = models.IntegerField(choices=ACTIVITIES, verbose_name='Forma działania')
    activity_comment = models.TextField(verbose_name='Dodatkowe informacje', null=True, blank=True)
    activity_done = models.BooleanField(null=True, verbose_name='Wykonane', default=False)
    history = HistoricalRecords()
    # def __str__(self):
    #     return str(self.activity_type[1])

salesleads/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views import View
from django.views.generic import ListView, UpdateView, DeleteView, CreateView
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.template.loader import render_to_string
from django.http import JsonResponse, HttpResponseRedirect
from simple_history.utils import update_change_reason
from django.utils import timezone
from django import template

from salesleads.multiform import MultiFormsView

from salesleads.forms import (
    ChangeUserForm,
    ContactPersonForm,
    CommentForm,
    CountryForm,
    LoginForm,
    MyGeoForm,
    PlannedActivitiesAddForm,
    PlannedActivitiesUpdateForm,
    SalesLeadAddForm,
    SalesLeadAddressAddForm,
    ReportForm
)
from salesleads.models import Comment, ExportUser, SalesLead, PlannedActivities, ContactPerson, Country, STATUS


def get_saleslead(id):
    return SalesLead.objects.get(pk=id)


def get_user(id):
    return ExportUser.objects.get(pk=id)


def get_user_id(username):
    return ExportUser.objects.get(username=username).id


def is_valid_query(param):
    return param != '' and param is not None and param != 'None'


class LoginView(View):
    def get(self, request):
        form = LoginForm()
        ctx = {
            'form': form
        }
        return render(request, 'salesleads/login.html', ctx)

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            export_user = authenticate(**form.cleaned_data)
            if export_user is not None:
                login(request, export_user)
                return redirect('dashboard')
        return render(request, 'salesleads/login.html', {'form': form})


class LogoutView(View):
    def get(self, request):
        if request.user.is_authenticated:
            logout(request)
            return redirect('login')


class UserListView(ListView):
    model = ExportUser
    template_name = 'salesleads/users.html'


class DashboardView(LoginRequiredMixin, View):
    def get(self, request):
        user = self.request.user
        salesleads = SalesLead.objects.filter(user=user)
        activities = PlannedActivities.objects.filter(user=user).filter(
            Q(activity_done=False) | Q(activity_done=None)).filter(date__gte=timezone.now()).order_by('date')
        status_one = 0
        status_two = 0
        status_three = 0
        status_four = 0
        status_five = 0

        page_number = request.GET.get('page')

        # Time filters for 1st sector
        this_week = request.GET.get('this_week')
        this_month = request.GET.get('this_month')
        this_quarter = request.GET.get('this_quarter')
        this_year = request.GET.get('this_year')
        last_year = request.GET.get('last_year')

        # Actions filters for 2nd sector
        to_do = request.GET.get('todo')
        done = request.GET.get('done')
        overdue = request.GET.get('overdue')

        if this_week == 'True':
            salesleads = salesleads.filter(created__week_day=timezone.now().weekday())
        if this_month == 'True':
            salesleads = salesleads.filter(created__month=timezone.now().month)
        if this_quarter == 'True':
            pass
        if this_year == 'True':
            salesleads = salesleads.filter(created__year=timezone.now().year)
        if last_year == 'True':
            pass

        if to_do == 'True':
            activities = PlannedActivities.objects.filter(user=user).filter(
                Q(activity_done=False) | Q(activity_done=None)).filter(date__gte=timezone.now()).order_by('date')
        if done == 'True':
            activities = PlannedActivities.objects.filter(user=user).filter(activity_done=True).order_by('date')
        if overdue == 'True':
            activities = PlannedActivities.objects.filter(user=user).filter(date__lt=timezone.now()).exclude(activity_done=True).order_by('date')

        paginator = Paginator(activities, 5)
        page_obj = paginator.get_page(page_number)

        for lead in salesleads:
            if lead.status == 1:
                status_one += 1
            if lead.status == 2:
                status_two += 1
            if lead.status == 3:
                status_three += 1
            if lead.status == 4:
                status_four += 1
            if lead.status == 5:
                status_five += 1

        saleslead_history = SalesLead.history.filter(history_user=user)
        comment_history = Comment.history.filter(history_user=user)
        contactperson_history = ContactPerson.history.filter(history_user=user)
        plannedactivity_history = PlannedActivities.history.filter(history_user=user)

        together = []

        for item in comment_history:
            try:
                saleslead = get_saleslead(item.saleslead_id)
            except:
                saleslead = None
            together.append([item.history_date, saleslead, item.get_history_type_display,
                             item.history_change_reason, get_user(item.history_user_id), item.id, 'comment'])
        for item in contactperson_history:
            try:
                saleslead = get_saleslead(item.saleslead_id)
            except:
                saleslead = None
            together.append([item.history_date, saleslead, item.get_history_type_display, item.history_change_reason,
                             get_user(item.history_user_id), item.id, 'contactperson'])
        for item in plannedactivity_history:
            try:
                saleslead = get_saleslead(item.saleslead_id)
            except:
                saleslead = None
            together.append([item.history_date, saleslead, item.get_history_type_display,
                             item.history_change_reason, get_user(item.history_user_id), item.id, 'plannedactivity'])
        for item in saleslead_history:
            try:
                saleslead = item.company_name
            except:
                saleslead = None
            together.append(
                [item.history_date, saleslead, item.get_history_type_display, item.history_change_reason,
                 get_user(item.history_user_id), item.id, 'saleslead'])

        together = sorted(together, key=lambda x: x[0], reverse=True)

        ctx = {
            'status_one': status_one,
            'status_two': status_two,
            'status_three': status_three,
            'status_four': status_four,
            'status_five': status_five,
            'page_obj': page_obj,
            'user': user,
            'together': together,
            'todo': to_do,
            'done': done,
            'overdue': overdue,
        }
        return render(request, 'salesleads/dashboard.html', ctx)


class SalesLeadAddFormView(LoginRequiredMixin, View):
    def get(self, request):
        form = SalesLeadAddForm()
        ctx = {
            'form': form
        }
        return render(request, 'salesleads/saleslead_add.html', ctx)

    def post(self, request):
        form = SalesLeadAddForm(request.POST)
        if form.is_valid():
            new_saleslead = SalesLead.objects.create(user=self.request.user, **form.cleaned_data)
            update_change_reason(new_saleslead, f'{new_saleslead.company_name}')
            return redirect('salesleads')
        return render(request, 'salesleads/saleslead_add.html', {'form': form})


class SalesLeadListView(LoginRequiredMixin, View):
    def get(self, request):
        salesleads = SalesLead.objects.filter(user=self.request.user)
        ctx = {
            'salesleads': salesleads,
        }
        return render(request, 'salesleads/saleslead_list.html', ctx)


class SalesLeadDelete(LoginRequiredMixin, DeleteView):
    model = SalesLead
    pk_url_kwarg = 'saleslead_id'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        name = self.object.company_name
        self.object.delete()
        update_change_reason(self.object, f'{name}')
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('salesleads')

    def get(self, request, *args, **kwargs):
        return self.delete(request, *args, **kwargs)

class SalesLeadModalDelete(LoginRequiredMixin, View):
    def get(self, request, saleslead_id):
        saleslead = SalesLead.objects.get(pk=saleslead_id)
        ctx = {
            'saleslead':saleslead
        }
        return render(request, 'salesleads/saleslead_delete_modal.html', ctx)
    def post(self, request, saleslead_id):
        saleslead = SalesLead.objects.get(pk=saleslead_id)
        saleslead.delete()
        update_change_reason(saleslead, f'{saleslead.company_name}')
        return redirect('salesleads')




class SalesLeadDetailView(LoginRequiredMixin, MultiFormsView):
    template_name = 'salesleads/saleslead_detail.html'
    form_classes = {'updatelead': SalesLeadAddForm,
                    'commentadd': CommentForm,
                    'contactpersonform': ContactPersonForm,
                    'updateaddress': SalesLeadAddressAddForm,
                    'plannedactivitiesaddform': PlannedActivitiesAddForm,
                    'plannedactivitiesupdateform': PlannedActivitiesUpdateForm,
                    'mygeoform': MyGeoForm,
                    'countryaddform': CountryForm}
    success_url = '/'

    def get_updatelead_initial(self):
        saleslead_id = self.kwargs['saleslead_id']
        saleslead = SalesLead.objects.get(pk=saleslead_id)
        ctx = model_to_dict(saleslead)
        return ctx

    def get_updateaddress_initial(self):
        saleslead_id = self.kwargs['saleslead_id']
        saleslead = SalesLead.objects.get(pk=saleslead_id)
        ctx = model_to_dict(saleslead)

salesleads/templates/notused/comment_add.html
{% extends 'salesleads/base.html' %}
{% block title %}Dodaj lead{% endblock %}
{% block content %}
    <div class="container">
        <h1>Dodaj komentarz dla: {{ saleslead.company_name }}</h1>
        <form action="{% url 'comment-add' saleslead.id %}" method="POST">
            {% csrf_token %}
            {{ form.as_ul }}
            <input type="submit" value="Dodaj">
        </form>
    </div>
{% endblock %}

salesleads/templates/notused/dashboard.html
{% extends 'salesleads/base.html' %}
{% load leaflet_tags %}
{% leaflet_js %}
{% leaflet_css %}
{% block title %}Dashboard{% endblock %}
{% block content %}
    <div class="container">
        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab"
                   aria-controls="pills-home" aria-selected="true">All</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab"
                   aria-controls="pills-home" aria-selected="true">2020</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab"
                   aria-controls="pills-profile" aria-selected="false">Kwartał</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab"
                   aria-controls="pills-contact" aria-selected="false">Miesiąc</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="pills-contact-tab" data-toggle="pill" href="#pills-contact" role="tab"
                   aria-controls="pills-contact" aria-selected="false">Tydzień</a>
            </li>
        </ul>
    </div>
    <div class="container">

        <div class="tab-content" id="pills-tabContent">
            <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">

                <div class="col-md-12">
                    <div class="card bg-light mb-3">
                        <div class="card-header">Nazwa użytkownika: {{ user }}</div>

                        <div class="card-body">
                            <h5 class="card-title">Podsumowanie lead'ow</h5>
                            <p class="card-text">
                            <div class="row">
                                <div class="col-md-2 offset-md-1">
                                    <div class="card text-white bg-success mb-3" style="max-width: 18rem;">
                                        <div class="card-header">Pierwsze zamówienie</div>
                                        <div class="card-body">
                                            <h3 class="card-title">{{ status_one }}</h3>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="card text-white bg-warning mb-3" style="max-width: 18rem;">
                                        <div class="card-header">Złożone warunki/oferta</div>
                                        <div class="card-body">
                                            <h3 class="card-title">{{ status_two }}</h3>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="card text-white bg-primary mb-3" style="max-width: 18rem;">
                                        <div class="card-header">Najbardziej obiecujące</div>
                                        <div class="card-body">
                                            <h3 class="card-title">{{ status_three }}</h3>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="card text-white bg-secondary mb-3" style="max-width: 18rem;">
                                        <div class="card-header">Pozostałe aktywności</div>
                                        <div class="card-body">
                                            <h3 class="card-title">{{ status_four }}</h3>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-2">
                                    <div class="card text-white bg-danger mb-3" style="max-width: 18rem;">
                                        <div class="card-header">Odrzucone leady</div>
                                        <div class="card-body">
                                            <h3 class="card-title">{{ status_five }}</h3>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            </p>
                        </div>


                        <div class="card-body">
                            <h5 class="card-title">Lista zaplanowanych działań</h5>
                            <p class="card-text">
                            <table class="table table-sm table-hover">
                                <tr>
                                    <th style="width: 20%">Data</th>
                                    <th style="width: 20%">Nazwa firmy</th>
                                    <th style="width: 20%">Typ</th>
                                    <th style="width: 35%">Komentarz</th>
                                    <th style="width: 5%">Wykonane</th>
                                </tr>
                                {% for activity in activities %}
                                    <tr>
                                        <td>{{ activity.date|date:"d E Y" }}</td>
                                        <td>{{ activity.saleslead.company_name }}</td>
                                        <td>{{ activity.get_activity_type_display }}</td>
                                        <td>{{ activity.activity_comment }}</td>
                                        <td>{{ activity.activity_done }}</td>
                                    </tr>
                                {% endfor %}
                            </table>
                            </p>
                        </div>

                        <div class="card-body">
                            <h5 class="card-title">Lista ostatnich 10 aktywności</h5>
                            <p class="card-text">
                            <table class="table table-sm table-hover">
                                <tr>
                                    <th style="width: 20%">Data</th>
                                    <th style="width: 20%">Lead</th>
                                    <th style="width: 20%">Akcja</th>
                                    <th style="width: 20%">Typ</th>
                                </tr>
                                {% for t in together|slice:":10" %}
                                    <tr>
                                        <td>{{ t.0 }}</td>
                                        <td>{{ t.1 }}</td>
                                        <td>{{ t.2 }}</td>
                                        <td><a href="">{{ t.3 }}</a></td>
                                    </tr>
                                {% endfor %}
                            </table>
                            </p>
                        </div>


                    </div>


                </div>


            </div>
            <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">...</div>
            <div class="tab-pane fade" id="pills-contact" role="tabpanel" aria-labelledby="pills-contact-tab">...</div>
        </div>
    </div>

    {% include 'salesleads/footer_sticky.html' %}
{% endblock %}

salesleads/templates/notused/login2.html
{% extends 'salesleads/base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
<div class="container-fluid">
  <div class="row no-gutter">
    <div class="d-none d-md-flex col-md-4 col-lg-6 bg-image"></div>
    <div class="col-md-8 col-lg-6">
      <div class="login d-flex align-items-center py-5">
        <div class="container">
          <div class="row">
            <div class="col-md-9 col-lg-8 mx-auto">
              <h3 class="login-heading mb-4">Welcome back!</h3>
                <div class="form-label-group">
                  <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
                  <label for="inputEmail">Email address</label>
                </div>

                <div class="form-label-group">
                  <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
                  <label for="inputPassword">Password</label>
                </div>

                <div class="custom-control custom-checkbox mb-3">
                  <input type="checkbox" class="custom-control-input" id="customCheck1">
                  <label class="custom-control-label" for="customCheck1">Remember password</label>
                </div>
                <button class="btn btn-lg btn-primary btn-block btn-login text-uppercase font-weight-bold mb-2" type="submit">Sign in</button>
                <div class="text-center">
                  <a class="small" href="#">Forgot password?</a></div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

salesleads/templates/notused/saleslead_confirm_delete.html
{% extends 'salesleads/base.html' %}
{% block title %}Usuwanie{% endblock %}
{% block content %}
    <form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>

{% endblock %}

salesleads/templates/notused/saleslead_d.html
{% extends 'salesleads/base.html' %}
{% block title %}Dodaj lead{% endblock %}
{% block content %}
    <div class="container">
        <h1>Dodaj Lead</h1>
        <form action="{% url 'saleslead-update' saleslead.id %}" method="POST">
            {% csrf_token %}
            {{ form.as_ul }}
            <input type="submit" value="Updatuj">
        </form>
    </div>
{% endblock %}

salesleads/templates/notused/saleslead_dashboard.html
{% extends 'salesleads/base.html' %}
{% block title %}Szczegóły {{ saleslead.company_name }}{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                {% include 'salesleads/../notused/saleslead_d.html' %}
            </div>
            <div class="col-md-6">
                {% include 'salesleads/../notused/comment_add.html' %}
            </div>
        </div>
    </div>


{% endblock %}

salesleads/templates/notused/test.html
{% extends 'salesleads/base.html' %}
{% block title %}Szczegóły {{ saleslead.company_name }}{% endblock %}
{% block content %}

<form class="login" method="POST" action="{% url 'saleslead-detail' saleslead.id %}">
    {% csrf_token %}
    {{ forms.login.as_p }}

    <button name='action' value='login' type="submit">Sign in</button>
</form>

<form class="signup" method="POST" action="{% url 'saleslead-detail' saleslead.id %}">
    {% csrf_token %}
    {{ forms.signup.as_p }}

    <button name='action' value='signup' type="submit">Sign up</button>
</form>

{% endblock %}

salesleads/templates/notused/test2.html
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" name="form" value="Submit" />
</form>

<form method="post">
    {% csrf_token %}
    {{ form2 }}
    <input type="submit" name="form2" value="Submit" />
</form>